### ISSUE TITLE
Doesn't work with AWS SSO

### ISSUE THREAD

**Issue by dsielert** [morincer/teamcity-plugin-saml#22] opened 2020-01-31 17:50 UTC
May relate to #19 
I login from the AWS side and it just directs me to the login page.. I'm unable to find any logging to see whats going on... Can provide more information as required

**Comment by davidsielert** [comment] 2020-02-02 23:22
This is a dupe of #20  closing

**Closed** 2020-02-03 09:47 UTC

**Comment by Gman54** [comment] 2020-12-18 20:51
We are using TeamCity Enterprise 2020.1 (build 78475) when clicking on the AWS SSO file for TeamCity we go directly to the TeamCity login page, it does not sign us in directly . The SSO login button will work and allows us to login.

**Comment by morincer** [comment] 2020-12-18 21:09
Hi @Gman54 
Please refer to https://github.com/morincer/teamcity-plugin-saml#troubleshooting 
If nothing helps - pls collect logs and create a separate issue.
